spring:
  application:
    name: stringpro
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.lausi95.net/realms/stringpro
  docker:
    compose:
      enabled: false
  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/stringpro}
    username: ${MONGODB_USERNAME:root}
    password: ${MONGODB_PASSWORD:example}

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: info
